[project]
name = "karp-s-backend"
version = "1.0.0-dev"
description = "Structed data infrastructure"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "PyYAML==6.0.2",
    "mysql-connector-python",
    "environs",
    "pyjwt[crypto]>=2.11.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.29.2",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "ruff>=0.9.2",
    "syrupy>=4.9.1",
    "tatsu>=5.13.1",
]
